### ISSUE TITLE
How can I run this code on our own dataset

### ISSUE THREAD

**Issue by MiaoHu-Pro** [ralphabb/BoxE#3]
Hi, thank for your good job, I want to know How can I run this code on our own dataset?

hope for your answer~~

@ralphabb @ismaililkanc

**Comment by ralphabb** [comment]
Hi MiaoHu, 
You can run a custom dataset by putting it in the corresponding folder (DatasetsMulti) in the right format (txt files for train, test, valid, consisting of fact lines following the format: relation, head, tail), and then running KBUtils.py. I hope this helps! 
Best,
Ralph
